services:

  app:
    image: dunglas/frankenphp:1-php8.4
    working_dir: /app
    volumes:
      - .:/app
      - app_storage:/app/storage
      - ./.caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.php/99-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: "http://localhost:8080"
      CADDY_GLOBAL_OPTIONS: "auto_https off"
      SERVICE_CONTAINER_WRAPPER: "/app/config/container.php"
    ports:
      - 8080:8080
    tty: true

volumes:
  caddy_data:
  caddy_config:
  app_storage:
